using System;

namespace Verse;

public static class ThingRequestGroupUtility
{
	public static bool StoreInRegion(this ThingRequestGroup group)
	{
		return group switch
		{
			ThingRequestGroup.Undefined => false, 
			ThingRequestGroup.Nothing => false, 
			ThingRequestGroup.Everything => true, 
			ThingRequestGroup.HaulableEver => true, 
			ThingRequestGroup.HaulableAlways => true, 
			ThingRequestGroup.FoodSource => true, 
			ThingRequestGroup.MechCharger => true, 
			ThingRequestGroup.FoodSourceNotPlantOrTree => true, 
			ThingRequestGroup.Corpse => true, 
			ThingRequestGroup.Blueprint => true, 
			ThingRequestGroup.BuildingArtificial => true, 
			ThingRequestGroup.BuildingFrame => true, 
			ThingRequestGroup.Pawn => true, 
			ThingRequestGroup.PotentialBillGiver => true, 
			ThingRequestGroup.Medicine => true, 
			ThingRequestGroup.Filth => true, 
			ThingRequestGroup.AttackTarget => true, 
			ThingRequestGroup.Weapon => true, 
			ThingRequestGroup.Apparel => true, 
			ThingRequestGroup.Refuelable => true, 
			ThingRequestGroup.HaulableEverOrMinifiable => true, 
			ThingRequestGroup.Drug => true, 
			ThingRequestGroup.Shell => true, 
			ThingRequestGroup.HarvestablePlant => true, 
			ThingRequestGroup.Fire => true, 
			ThingRequestGroup.Plant => true, 
			ThingRequestGroup.NonStumpPlant => true, 
			ThingRequestGroup.Bed => true, 
			ThingRequestGroup.Chunk => true, 
			ThingRequestGroup.Seed => true, 
			ThingRequestGroup.WasteProducer => true, 
			ThingRequestGroup.Book => true, 
			ThingRequestGroup.PsychicRitualSpot => true, 
			ThingRequestGroup.EntityHolder => true, 
			ThingRequestGroup.PassengerShuttle => true, 
			ThingRequestGroup.Fish => true, 
			ThingRequestGroup.Construction => false, 
			ThingRequestGroup.HasGUIOverlay => false, 
			ThingRequestGroup.MinifiedThing => false, 
			ThingRequestGroup.Grave => false, 
			ThingRequestGroup.Art => false, 
			ThingRequestGroup.ThingHolder => false, 
			ThingRequestGroup.ActiveTransporter => false, 
			ThingRequestGroup.Transporter => false, 
			ThingRequestGroup.LongRangeMineralScanner => false, 
			ThingRequestGroup.AffectsSky => false, 
			ThingRequestGroup.WindSource => false, 
			ThingRequestGroup.AlwaysFlee => false, 
			ThingRequestGroup.ResearchBench => false, 
			ThingRequestGroup.Facility => false, 
			ThingRequestGroup.AffectedByFacilities => false, 
			ThingRequestGroup.CreatesInfestations => false, 
			ThingRequestGroup.WithCustomRectForSelector => false, 
			ThingRequestGroup.ProjectileInterceptor => false, 
			ThingRequestGroup.ConditionCauser => false, 
			ThingRequestGroup.MusicalInstrument => false, 
			ThingRequestGroup.MusicSource => false, 
			ThingRequestGroup.Throne => false, 
			ThingRequestGroup.FoodDispenser => false, 
			ThingRequestGroup.Projectile => false, 
			ThingRequestGroup.MeditationFocus => false, 
			ThingRequestGroup.DryadSpawner => false, 
			ThingRequestGroup.Studiable => false, 
			ThingRequestGroup.Suppressable => false, 
			ThingRequestGroup.ActionDelay => false, 
			ThingRequestGroup.MechGestator => false, 
			ThingRequestGroup.GenepackHolder => false, 
			ThingRequestGroup.Dissolving => false, 
			ThingRequestGroup.SubcoreScanner => false, 
			ThingRequestGroup.Styleable => false, 
			ThingRequestGroup.BossgroupCaller => false, 
			ThingRequestGroup.WakeUpDormant => false, 
			ThingRequestGroup.Atomizer => false, 
			ThingRequestGroup.PowerTrader => false, 
			ThingRequestGroup.HoldingPlatformTarget => false, 
			ThingRequestGroup.MapPortal => false, 
			ThingRequestGroup.BuildingGroundSpawner => false, 
			ThingRequestGroup.SubstructureFootprint => false, 
			ThingRequestGroup.Hackable => false, 
			ThingRequestGroup.Door => false, 
			ThingRequestGroup.CostProvider => false, 
			ThingRequestGroup.ApparelSource => false, 
			_ => throw new ArgumentException("group"), 
		};
	}
}
